name: "Team Peggle"
subtitle: "Straight up Pegglin"

markdown: kramdown

markdown_ext:  markdown,md

contact:
    steam: "http://steamcommunity.com/groups/TEAMPEGGLE"
    email: "badmin@teampeggle.com"

analytics_id: "UA-57393752-1"
